"use client";

import { FormEvent, useMemo, useState, useTransition } from "react";
import { TableStatus } from "@/generated/prisma/enums";

type Table = { id: string; tableNumber: string; name: string | null; capacity: number; status: TableStatus };
type Section = { id: string; name: string; description: string | null; isActive: boolean; tables: Table[] };
type Floor = { id: string; name: string; description: string | null; isActive: boolean; sections: Section[]; tables: Table[] };
const labels: Record<TableStatus, string> = { AVAILABLE: "Available", OCCUPIED: "Occupied", RESERVED: "Reserved", PREPARING: "Preparing", READY: "Ready", BILL_REQUESTED: "Bill requested", CLEANING: "Cleaning", OUT_OF_SERVICE: "Out of service" };
const styles: Record<TableStatus, string> = { AVAILABLE: "border-emerald-200 bg-emerald-50 text-emerald-700", OCCUPIED: "border-red-200 bg-red-50 text-red-700", RESERVED: "border-blue-200 bg-blue-50 text-blue-700", PREPARING: "border-amber-200 bg-amber-50 text-amber-700", READY: "border-violet-200 bg-violet-50 text-violet-700", BILL_REQUESTED: "border-orange-200 bg-orange-50 text-orange-700", CLEANING: "border-slate-200 bg-slate-100 text-slate-700", OUT_OF_SERVICE: "border-slate-300 bg-slate-200 text-slate-600" };

export default function TablesClient({ branchName, floors }: { branchName: string; floors: Floor[] }) {
  const [layout, setLayout] = useState(floors), [floorId, setFloorId] = useState(floors[0]?.id ?? ""), [sectionId, setSectionId] = useState(""), [search, setSearch] = useState(""), [filter, setFilter] = useState<"ALL" | TableStatus>("ALL"), [modal, setModal] = useState<"add-floor" | "edit-floor" | "add-section" | "edit-section" | "add-table" | "edit-table" | null>(null), [selected, setSelected] = useState<Table | null>(null), [message, setMessage] = useState(""), [pending, startTransition] = useTransition();
  const floor = layout.find((item) => item.id === floorId) ?? layout[0]; const section = sectionId === "DIRECT" ? undefined : floor?.sections.find((item) => item.id === sectionId) ?? floor?.sections[0];
  const tables = useMemo(() => [...(section?.tables ?? []), ...(section ? [] : floor?.tables ?? [])], [section, floor]); const visible = useMemo(() => tables.filter(t => (!search || `${t.tableNumber} ${t.name ?? ""}`.toLowerCase().includes(search.toLowerCase())) && (filter === "ALL" || t.status === filter)), [tables, search, filter]);
  const refreshLayout = async () => {
    const response = await fetch("/api/tables", { cache: "no-store" });
    const result = await response.json() as { data?: { name?: string; floors?: Floor[] }; error?: { message?: string } };
    if (!response.ok || !result.data?.floors) throw new Error(result.error?.message ?? "Unable to reload table data.");
    setLayout(result.data.floors);
    if (selected) {
      const updated = result.data.floors.flatMap(item => [...item.tables, ...item.sections.flatMap(value => value.tables)]).find(item => item.id === selected.id);
      setSelected(updated ?? null);
    }
  };
  const mutate = async (action: string, input: Record<string, unknown> = {}) => {
    const response = await fetch("/api/tables", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...input }) });
    const result = await response.json() as { error?: { message?: string } };
    if (!response.ok) throw new Error(result.error?.message ?? "Unable to save.");
  };
  const run = (action: string, input: Record<string, unknown> = {}) => startTransition(async () => { try { await mutate(action, input); await refreshLayout(); setMessage("Saved."); setModal(null); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save."); } });
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const name = String(f.get("name") ?? ""); const description = String(f.get("description") ?? ""); const tableInput = { floorId: floor?.id, sectionId: section?.id, tableNumber: String(f.get("tableNumber")), name: String(f.get("displayName") ?? "") || undefined, capacity: Number(f.get("capacity")), status: String(f.get("status")) as TableStatus }; if (modal === "edit-floor" && floor) run("update-floor", { floorId: floor.id, name, description }); else if (modal === "add-floor") run("create-floor", { name, description }); else if (modal === "edit-section" && section) run("update-section", { sectionId: section.id, name, description }); else if (modal === "add-section" && floor) run("create-section", { floorId: floor.id, name, description }); else if (modal === "add-table" && floor) run("create-table", tableInput); else if (modal === "edit-table" && floor && selected) run("update-table", { ...tableInput, tableId: selected.id }); };
  const openTable = (table?: Table) => { setSelected(table ?? null); setModal(table ? "edit-table" : "add-table"); };
  const allFloorTables = [...(floor?.tables ?? []), ...(floor?.sections.flatMap(item => item.tables) ?? [])];
  const statusCounts = Object.values(TableStatus).map(status => [status, allFloorTables.filter(table => table.status === status).length] as const);
  return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 sm:p-6" aria-busy={pending}>
    <header className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-slate-500">{branchName}</p><h1 className="text-3xl font-bold">Restaurant Layout</h1><p className="text-slate-500">Database-backed floor, section and table configuration.</p></div><button onClick={() => setModal("add-floor")} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white">+ Add Floor</button></header>
    {message && <p className="mt-4 rounded-lg bg-white p-3 text-sm">{message}</p>}
    {!floors.length ? <div className="mt-8 rounded-2xl border bg-white p-10 text-center"><h2 className="text-xl font-bold">No floors configured</h2><button onClick={() => setModal("add-floor")} className="mt-4 rounded-xl bg-slate-900 px-4 py-2 text-white">Add Floor</button></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]">
      <aside className="space-y-2"><p className="text-xs font-bold uppercase text-slate-400">Floors</p>{layout.map(f => <button disabled={pending} key={f.id} onClick={() => { setFloorId(f.id); setSectionId(""); }} className={`w-full rounded-xl border p-3 text-left font-semibold ${f.id === floor?.id ? "bg-slate-900 text-white" : "bg-white"}`}>{f.name}<span className="block text-xs font-normal opacity-70">{f.sections.length} sections · {f.tables.length} direct tables</span></button>)}{floor && <div className="flex flex-wrap gap-2 pt-2"><button disabled={pending} onClick={() => setModal("edit-floor")} className="rounded border bg-white px-2 py-1 text-xs">Edit</button><button disabled={pending} onClick={() => run("reorder-floor", { floorId: floor.id, direction: "up" })} className="rounded border bg-white px-2 py-1 text-xs">↑</button><button disabled={pending} onClick={() => run("reorder-floor", { floorId: floor.id, direction: "down" })} className="rounded border bg-white px-2 py-1 text-xs">↓</button><button disabled={pending} onClick={() => run("set-floor-active", { floorId: floor.id, isActive: !floor.isActive })} className="rounded border bg-white px-2 py-1 text-xs">{floor.isActive ? "Deactivate" : "Activate"}</button><button disabled={pending} onClick={() => window.confirm("Delete this floor only when safe?") && run("delete-floor", { floorId: floor.id })} className="rounded border bg-white px-2 py-1 text-xs text-red-600">Delete</button></div>}</aside>
      <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{floor?.name}</h2><p className="text-sm text-slate-500">{floor?.description || "Operational layout workspace"}</p></div><button onClick={() => setModal("add-section")} className="rounded-xl border px-4 py-2 text-sm font-semibold">+ Add Section</button></div>
        <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Total", allFloorTables.length], ...statusCounts.filter(([, count]) => count > 0).slice(0, 3).map(([status, count]) => [labels[status], count])].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</div>
        <div className="mt-5 flex flex-wrap gap-2">{floor?.sections.map(s => <button key={s.id} onClick={() => setSectionId(s.id)} className={`rounded-xl border px-4 py-2 text-sm ${s.id === section?.id ? "bg-slate-900 text-white" : "bg-white"}`}>{s.name} ({s.tables.length})</button>)}<button onClick={() => { setSectionId("DIRECT"); setSelected(null); }} className={`rounded-xl border px-4 py-2 text-sm ${sectionId === "DIRECT" ? "bg-slate-900 text-white" : "bg-white"}`}>Direct floor tables ({floor?.tables.length ?? 0})</button></div>
        {section && <div className="mt-4 flex gap-2"><button onClick={() => setModal("edit-section")} className="rounded border px-3 py-1 text-xs">Edit Section</button><button onClick={() => run("set-section-active", { sectionId: section.id, isActive: !section.isActive })} className="rounded border px-3 py-1 text-xs">{section.isActive ? "Deactivate" : "Activate"}</button><button onClick={() => window.confirm("Delete this section only when safe?") && run("delete-section", { sectionId: section.id })} className="rounded border px-3 py-1 text-xs text-red-600">Delete</button></div>}
        <div className="mt-5 flex flex-wrap gap-2"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search table number/name" className="rounded-lg border p-2 text-sm" /><select value={filter} onChange={e => setFilter(e.target.value as "ALL" | TableStatus)} className="rounded-lg border p-2 text-sm"><option value="ALL">All statuses</option>{Object.values(TableStatus).map(s => <option key={s} value={s}>{labels[s]}</option>)}</select><button onClick={() => openTable()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">+ Add Table</button></div>
        <p className="mt-3 text-sm text-slate-500">{visible.length} shown / {tables.length} active tables</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{visible.map(t => <button key={t.id} onClick={() => openTable(t)} className={`rounded-2xl border p-4 text-left ${styles[t.status]}`}><b>{t.name || `Table ${t.tableNumber}`}</b><span className="block text-xs">#{t.tableNumber} · {t.capacity} seats</span><span className="mt-2 block text-xs font-semibold">{labels[t.status]}</span></button>)}</div>{!visible.length && <p className="mt-4 rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No tables in this layout.</p>}
      </section></div>}
    {modal && <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-900/40 p-4"><form onSubmit={submit} className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold">{modal === "add-floor" ? "Add Floor" : modal === "edit-floor" ? "Edit Floor" : modal === "add-section" ? "Add Section" : modal === "edit-section" ? "Edit Section" : modal === "edit-table" ? "Edit Table" : "Add Table"}</h2>{(modal === "add-floor" || modal === "edit-floor" || modal === "add-section" || modal === "edit-section") && <><label className="block text-sm">Name<input name="name" required defaultValue={modal.includes("floor") ? floor?.name : section?.name} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm">Description<textarea name="description" defaultValue={modal.includes("floor") ? floor?.description ?? "" : section?.description ?? ""} className="mt-1 w-full rounded-lg border p-2" /></label></>}{(modal === "add-table" || modal === "edit-table") && <><label className="block text-sm">Table Number<input name="tableNumber" required defaultValue={selected?.tableNumber} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm">Display Name<input name="displayName" defaultValue={selected?.name ?? ""} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm">Capacity<input name="capacity" type="number" min="1" required defaultValue={selected?.capacity ?? 4} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm">Status<select name="status" defaultValue={selected?.status ?? "AVAILABLE"} className="mt-1 w-full rounded-lg border p-2">{Object.values(TableStatus).map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label></>}{selected && <div className="flex gap-2"><button type="button" disabled={pending} onClick={() => run("set-table-active", { tableId: selected.id, isActive: false })} className="rounded border px-3 py-2 text-xs">Deactivate</button><button type="button" disabled={pending} onClick={() => window.confirm("Delete this table when safe?") && run("delete-table", { tableId: selected.id })} className="rounded border px-3 py-2 text-xs text-red-600">Delete</button></div>}<div className="flex justify-end gap-2"><button type="button" disabled={pending} onClick={() => setModal(null)} className="rounded-lg border px-4 py-2">Cancel</button><button disabled={pending} className="rounded-lg bg-slate-900 px-4 py-2 text-white">{pending ? "Saving..." : "Save"}</button></div></form></div>}
  </main>;
}
