"use client";
type Report = { range: { days: number }; summary: { revenue: string; orders: number; bills: number; averageOrder: string }; paymentMethods: Record<string, string>; topItems: Array<{ itemName: string; quantity: number; revenue: string }>; recentBills: Array<{ id: string; billNumber: string; createdAt: Date | string; status: string; total: string }> };
export default function ReportsClient({ report }: { report: Report }) {
  return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl">
    <h1 className="text-3xl font-black">Reports</h1><p className="mb-6 text-sm text-slate-500">Last {report.range.days} days · database-backed sales and payment activity</p>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Revenue", `₹${report.summary.revenue}`], ["Orders", report.summary.orders], ["Bills", report.summary.bills], ["Average order", `₹${report.summary.averageOrder}`]].map(([label, value]) => <div className="rounded-2xl border bg-white p-5 shadow-sm" key={String(label)}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Payment methods</h2>{Object.entries(report.paymentMethods).map(([method, value]) => <div className="mt-3 flex justify-between border-b pb-2 text-sm" key={method}><span>{method}</span><b>₹{value}</b></div>)}</section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Top items</h2>{report.topItems.length ? report.topItems.map(item => <div className="mt-3 flex justify-between border-b pb-2 text-sm" key={item.itemName}><span>{item.itemName} × {item.quantity}</span><b>₹{item.revenue}</b></div>) : <p className="mt-3 text-sm text-slate-500">No item sales in this period.</p>}</section></div>
    <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent bills</h2><div className="mt-3 space-y-2">{report.recentBills.map(bill => <div className="flex justify-between border-b py-2 text-sm" key={bill.id}><span>{bill.billNumber} · {new Date(bill.createdAt).toLocaleDateString()}</span><span>{bill.status} · ₹{bill.total}</span></div>)}</div></section>
  </div></main>;
}
