/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useState } from "react";
type Bill = any;
type BillableOrder = any;
export default function BillingClient({ initialBills, initialBillableOrders }: { initialBills: Bill[]; initialBillableOrders: BillableOrder[] }) {
  const [bills, setBills] = useState(initialBills); const [orders, setOrders] = useState(initialBillableOrders); const [message, setMessage] = useState("");
  async function create(order: BillableOrder) {
    const r = await fetch("/api/billing", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "bill", orderId: order.id, idempotencyKey: `bill-${order.id}` }) });
    const data = await r.json(); if (!r.ok) return setMessage(data.error?.message); setBills(old => [data.data, ...old]); setOrders(old => old.filter(item => item.id !== order.id)); setMessage(`Created ${data.data.billNumber} for ${order.orderNumber}.`);
  }
  async function pay(bill: Bill) {
    const r = await fetch("/api/billing", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "payment", billId: bill.id, method: "CASH", amount: bill.total, idempotencyKey: `cash-${bill.id}` }) });
    const data = await r.json(); if (!r.ok) return setMessage(data.error?.message); setMessage("Payment recorded. Receipt is ready to print.");
  }
  return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl"><h1 className="mb-6 text-3xl font-black">Billing & Receipts</h1>{message && <p className="mb-4 rounded-lg bg-blue-100 p-3">{message}</p>}{orders.length > 0 && <section className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 className="mb-3 text-lg font-black">Ready to bill</h2><div className="space-y-2">{orders.map(order => <div key={order.id} className="flex flex-wrap items-center gap-3 rounded-lg bg-white p-3"><b>{order.orderNumber}</b><span>{order.orderType.replace("_", " ")}</span><span className="font-bold">₹{order.total}</span><button className="ml-auto rounded-lg bg-amber-600 px-4 py-2 font-bold text-white" onClick={() => create(order)}>Create bill</button></div>)}</div></section>}<div className="space-y-3">{bills.map(bill => <article key={bill.id} className="rounded-xl bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center gap-4"><b>{bill.billNumber}</b><span>{(bill.order as unknown as { orderNumber: string }).orderNumber}</span><span className="font-bold">₹{bill.total}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{bill.status}</span><div className="ml-auto flex gap-2">{bill.status === "OPEN" && <button className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white" onClick={() => pay(bill)}>Record cash payment</button>}{bill.status === "PAID" && <button className="rounded-lg bg-indigo-600 px-4 py-2 font-bold text-white" onClick={async () => { const r = await fetch("/api/billing", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "complete", orderId: (bill.order as unknown as { id: string }).id }) });   const d = await r.json(); setMessage(r.ok ? "Order completed and table released." : d.error?.message); }}>Complete order</button>}<button className="rounded-lg bg-slate-900 px-4 py-2 font-bold text-white" onClick={() => fetch("/api/billing", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "print", documentType: "RECEIPT", billId: bill.id, idempotencyKey: `receipt-${bill.id}` }) })}>Print receipt</button></div></div></article>)}{!bills.length && <p className="rounded-xl bg-white p-8 text-center">No bills yet. Use the ready-to-bill list above.</p>}</div><p className="mt-6 text-sm text-slate-500">Bills use server-side price snapshots. Print jobs are queued for a local print agent or browser printing.</p></div></main>;
}
